/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE, type PortfolioItem, type Testimonial, type PricingPackage, type ContactSubmission } from "./declarations/backend.did";
export type { PortfolioItem, Testimonial, PricingPackage, ContactSubmission };
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface backendInterface {
    _initializeAccessControlWithSecret(secret: string): Promise<undefined>;
    adminLogin(username: string, password: string): Promise<[] | [string]>;
    adminLogout(token: string): Promise<boolean>;
    checkSession(token: string): Promise<boolean>;
    getPortfolioItems(): Promise<Array<PortfolioItem>>;
    addPortfolioItem(token: string, title: string, cuisine: string, description: string, imageUrl: string, projectUrl: string): Promise<[] | [PortfolioItem]>;
    updatePortfolioItem(token: string, id: bigint, title: string, cuisine: string, description: string, imageUrl: string, projectUrl: string): Promise<boolean>;
    deletePortfolioItem(token: string, id: bigint): Promise<boolean>;
    getTestimonials(): Promise<Array<Testimonial>>;
    addTestimonial(token: string, clientName: string, restaurantName: string, location: string, quote: string, rating: bigint, avatarUrl: string): Promise<[] | [Testimonial]>;
    updateTestimonial(token: string, id: bigint, clientName: string, restaurantName: string, location: string, quote: string, rating: bigint, avatarUrl: string): Promise<boolean>;
    deleteTestimonial(token: string, id: bigint): Promise<boolean>;
    getPricingPackages(): Promise<Array<PricingPackage>>;
    addPricingPackage(token: string, name: string, price: string, description: string, features: string[], highlighted: boolean, ctaText: string): Promise<[] | [PricingPackage]>;
    updatePricingPackage(token: string, id: bigint, name: string, price: string, description: string, features: string[], highlighted: boolean, ctaText: string): Promise<boolean>;
    deletePricingPackage(token: string, id: bigint): Promise<boolean>;
    submitContact(name: string, email: string, phone: string, restaurantName: string, message: string): Promise<bigint>;
    getContactSubmissions(token: string): Promise<[] | [Array<ContactSubmission>]>;
    markContactRead(token: string, id: bigint): Promise<boolean>;
    deleteContactSubmission(token: string, id: bigint): Promise<boolean>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    _initializeAccessControlWithSecret(secret: string): Promise<undefined> { return this.actor._initializeAccessControlWithSecret(secret) as any; }
    adminLogin(username: string, password: string): Promise<[] | [string]> { return this.actor.adminLogin(username, password) as any; }
    adminLogout(token: string): Promise<boolean> { return this.actor.adminLogout(token) as any; }
    checkSession(token: string): Promise<boolean> { return this.actor.checkSession(token) as any; }
    getPortfolioItems(): Promise<Array<PortfolioItem>> { return this.actor.getPortfolioItems() as any; }
    addPortfolioItem(token: string, title: string, cuisine: string, description: string, imageUrl: string, projectUrl: string): Promise<[] | [PortfolioItem]> { return this.actor.addPortfolioItem(token, title, cuisine, description, imageUrl, projectUrl) as any; }
    updatePortfolioItem(token: string, id: bigint, title: string, cuisine: string, description: string, imageUrl: string, projectUrl: string): Promise<boolean> { return this.actor.updatePortfolioItem(token, id, title, cuisine, description, imageUrl, projectUrl) as any; }
    deletePortfolioItem(token: string, id: bigint): Promise<boolean> { return this.actor.deletePortfolioItem(token, id) as any; }
    getTestimonials(): Promise<Array<Testimonial>> { return this.actor.getTestimonials() as any; }
    addTestimonial(token: string, clientName: string, restaurantName: string, location: string, quote: string, rating: bigint, avatarUrl: string): Promise<[] | [Testimonial]> { return this.actor.addTestimonial(token, clientName, restaurantName, location, quote, rating, avatarUrl) as any; }
    updateTestimonial(token: string, id: bigint, clientName: string, restaurantName: string, location: string, quote: string, rating: bigint, avatarUrl: string): Promise<boolean> { return this.actor.updateTestimonial(token, id, clientName, restaurantName, location, quote, rating, avatarUrl) as any; }
    deleteTestimonial(token: string, id: bigint): Promise<boolean> { return this.actor.deleteTestimonial(token, id) as any; }
    getPricingPackages(): Promise<Array<PricingPackage>> { return this.actor.getPricingPackages() as any; }
    addPricingPackage(token: string, name: string, price: string, description: string, features: string[], highlighted: boolean, ctaText: string): Promise<[] | [PricingPackage]> { return this.actor.addPricingPackage(token, name, price, description, features, highlighted, ctaText) as any; }
    updatePricingPackage(token: string, id: bigint, name: string, price: string, description: string, features: string[], highlighted: boolean, ctaText: string): Promise<boolean> { return this.actor.updatePricingPackage(token, id, name, price, description, features, highlighted, ctaText) as any; }
    deletePricingPackage(token: string, id: bigint): Promise<boolean> { return this.actor.deletePricingPackage(token, id) as any; }
    submitContact(name: string, email: string, phone: string, restaurantName: string, message: string): Promise<bigint> { return this.actor.submitContact(name, email, phone, restaurantName, message) as any; }
    getContactSubmissions(token: string): Promise<[] | [Array<ContactSubmission>]> { return this.actor.getContactSubmissions(token) as any; }
    markContactRead(token: string, id: bigint): Promise<boolean> { return this.actor.markContactRead(token, id) as any; }
    deleteContactSubmission(token: string, id: bigint): Promise<boolean> { return this.actor.deleteContactSubmission(token, id) as any; }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
